server:
  port: 8082

spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///shopping?serverTimezone=Asia/Shanghai

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    instance-id: 180.208.42.83:8082


