server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: 180.208.42.83:10010
spring:
  application:
    name: zuul-service

zuul:
  prefix: /api
  routes:
    item-service: /item/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

#zuul:
#  routes:
#    user-service: /user-service/**
##      serviceId: user-service

#定义全局的线程隔离时长
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#负载均衡
ribbon:
  ConnectTimeout: 1000  #ribbon链接的超时时长
  ReadTimeout: 3500  #ribbon读取超时时长
  MaxAutoRetries: 0  #当前服务重试次数
  MaxAutoRetriesNextServer: 0  #切换服务重试次数

